### ISSUE TITLE
Diagram does not show up in the documentation "Usage"

### ISSUE THREAD

**Issue by krassowski** [jupyter/jupyter#700]
![Screenshot from 2023-10-11 16-25-57](https://github.com/jupyter/notebook/assets/5832902/db8c4bc4-a1da-404f-a0e2-e1d9eafa27f8)

**Comment by ivanov** [comment]
spoken like the man who broke it ;) - fixed in #712

**Comment by krassowski** [comment]
Does it work for you now? For me it still does not render so I am not convinced that the pr linked fixed it.

**Comment by krassowski** [comment]
Nor that the pr blamed broke it ;)

For context this is also broken in IPython docs.

**Comment by krassowski** [comment]
Reopening because it still does not work:

![image](https://github.com/jupyter/jupyter/assets/5832902/1a90bb96-b410-47b5-a02e-76c319f35e8f)

**Comment by krassowski** [comment]
Huh I do not even have rights to re-open my own issue.

**Comment by ivanov** [comment]
thanks for following up @krassowski , it worked for me locally to produce the same thing you saw in #714, i didn't realize that  the CI didn't have graphviz installed and was just blindly *hoping* that it would render on CI better than it did locally initially (which didn't happen). But we got that sorted now.

> For context this is also broken in IPython docs.

Where in the docs do you see this? I coudln't find a graphviz usage in there.

**Comment by krassowski** [comment]
>> For context this is also broken in IPython docs.
>
> Where in the docs do you see this? I coudln't find a graphviz usage in there.

That would be https://github.com/ipython/ipython/issues/14213

**Comment by ivanov** [comment]
thanks, added it to my little todo list.
