### ISSUE TITLE
icons invisible in dark mode

### ISSUE THREAD

**Issue by brownsarahm** [jupyter/jupyter#709]
In dark mode the search and dark/light mode on https://docs.jupyter.org/ are not visible until hover, they are visible on other projects though like https://jupyter-notebook.readthedocs.io/en/latest/

I'm in a managed chrome that does not allow any extensions. 
Version 118.0.5993.117 (Official Build) (x86_64)

![Screen Shot 2023-10-31 at 8 33 12 AM](https://github.com/jupyter/jupyter/assets/10656079/4edb858b-02f0-4a0a-8bd1-e913e0261479)

![Screen Shot 2023-10-31 at 8 33 58 AM](https://github.com/jupyter/jupyter/assets/10656079/5489892f-d684-47d6-8a38-5a12192e6b93)

**Comment by amoghak-ds** [comment]
I'd love to help on this issue, @brownsarahm. Please let me know if you've already started working on it.

**Comment by brownsarahm** [comment]
I have not worked on this.

**Comment by ivanov** [comment]
Thank you for the report. What operating system is this, by chance? I just tried on a similar version of chrome, and do not see this issue: Version 118.0.5993.70 (Official Build) built on Debian 12.2, running on Debian 12.2 (64-bit). 

It's also possible that it has been fixed in the time that this was reported, at the bottom of either page you'll see what theme is being used, which  currently reads

> Built with the [PyData Sphinx Theme](https://pydata-sphinx-theme.readthedocs.io/en/stable/index.html) 0.14.3.

If you are still seeing this issue, the proper place to report is over there: https://github.com/pydata/pydata-sphinx-theme/issues (and then we'll pick up those fixes in the various projects which use the pydata sphinx theme)

**Comment by brownsarahm** [comment]
I still see this problem, the reason I reported here and not pydata-sphinx is because the problem exists on this site, but not others that are using the same version of the pydata sphinx theme, so I suspected it was a setting or possibly custom css in this repo causing the problem.  The notebook docs linked above say they are using the same version of pydata theme, but on the same browser I can see. 

I'm on macos (11.2.3 with 2.3 GHz Quad-Core Intel Core i7) and now on chrome Version 119.0.6045.123 (Official Build) (x86_64)

**Comment by ivanov** [comment]
interesting - and weirdly, I now also see the problem you report on  https://docs.jupyter.org/
